# Generated by Django 2.2.4 on 2019-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('prodId', models.AutoField(primary_key=True, serialize=False)),
                ('prodName', models.CharField(max_length=255, unique=True)),
                ('prodType', models.CharField(max_length=20)),
                ('prodEventType', models.CharField(default='DEFAULT', max_length=20)),
                ('prodPrice', models.PositiveIntegerField()),
                ('prodCVS', models.CharField(default='DEFAULT', max_length=40)),
                ('prodImg', models.URLField(null=True)),
            ],
            options={
                'ordering': ['prodName'],
            },
        ),
    ]
